Enhancement: Fair play improvement
H3-gg/25th-Anniversary-Champioships pull request #2
Opened 2024-06-13 16:10 UTC by Kubaryt

2024-06-13 17:34 UTC, makiki99 requested changes

2024-06-13 17:34 UTC, makiki99 commented on pl/Regulamin_turnieju_Mistrzostwa_XXV-lecia_Heroes_of_Might_and_Magic_III.md
> +16. Zabrania się Uczestnikom celowego przedłużania Partii i nadużywania zegara w walce.
Raczej bym dał słowo "nadmiernego" zamiast "celowego" tutaj - odrobina stallu i granie pod late jest imo okej, bardziej imo chodzi o to żeby to nie było zwyczajnie zbyt mocne lub zbyt bezsensowne przeciąganie gry

2024-06-13 17:34 UTC, makiki99 commented on eng/Regulations_of_the_Heroes_of_Might_and_Magic_III_XXV_Anniversary_Championship_tournament.md
> +16. Participants are prohibited from intentionally prolonging a Party and abusing the timer during battles.
"excessively" zamiast "intentionally" - wyjaśnienie przy wersji PL

2024-06-13 17:34 UTC, makiki99 commented on pl/Regulamin_turnieju_Mistrzostwa_XXV-lecia_Heroes_of_Might_and_Magic_III.md
> +14. Rozmowy między Uczestnikami w trakcie trwania Partii powinny ograniczać się jedynie do kwestii koniecznych do wypełniania postanowień Zasad Mistrzostw, chyba, że obaj Uczestnicy wyrażą zgodę na p
Nie przepadam za sformułowaniem "chyba, że obaj Uczestnicy wyrażą zgodę na prowadzenie innej rozmowy." Co rozumiemy poprzez wyrażenie zgody?

2024-06-13 18:56 UTC, Kubaryt commented on pl/Regulamin_turnieju_Mistrzostwa_XXV-lecia_Heroes_of_Might_and_Magic_III.md
> +14. Rozmowy między Uczestnikami w trakcie trwania Partii powinny ograniczać się jedynie do kwestii koniecznych do wypełniania postanowień Zasad Mistrzostw, chyba, że obaj Uczestnicy wyrażą zgodę na p
Wg mnie stwierdzenie, z którego **jasno** wynika, że uczestnik nie ma nic przeciwko inny rozmowom, ciezko mi teraz wymyslic jakis niesztuczniebrzmiący przykład

2024-06-15 11:49 UTC, makiki99 approved these changes

2024-06-15 11:49 UTC, merged